DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  TITLE VARCHAR(250) NOT NULL,
  DESCRIPTION VARCHAR(250),
  FINISHED BIT(1),
  CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATE_BY VARCHAR(250),
  UPDATE_BY VARCHAR(250)
);
insert into TASK (TITLE,DESCRIPTION,FINISHED,CREATION_DATE,CREATE_BY)values('title1','description 1','false', NOW(), 'test1@user.com');
insert into TASK (TITLE,DESCRIPTION,FINISHED,CREATION_DATE,CREATE_BY)values('title2','description 2','false', NOW(), 'test2@user.com');
insert into TASK (TITLE,DESCRIPTION,FINISHED,CREATION_DATE,CREATE_BY)values('title3','description 3','false', NOW(), 'test3@user.com');
